"""ScenarioBank: pre-generated, fully deterministic evaluation scenarios.

Each scenario contains the COMPLETE dynamic trajectory the environment will
play back, independent of any policy:
  - user geometry (positions),
  - initial small-scale channels (h_d, G, g),
  - the Gauss-Markov innovation arrays for every step [max_steps, ...].

Because the environment plays these back verbatim (see
StarRisRsmaEnv.reset(options={"scenario": ...})), every evaluated method --
learned policies and classical baselines alike -- sees the identical geometry
and identical channel trajectory, regardless of its actions or its own RNG.
This is required for paired statistical comparisons.

Auditable seeding (item 7 reviewer fix)
---------------------------------------
Scenarios are generated by NESTED loops over (evaluation_seed, episode_idx).
Each scenario is derived deterministically from
`SeedSequence(entropy=evaluation_seed, spawn_key=(episode_idx,))`, and carries
its provenance explicitly: split, evaluation_seed, episode_idx and a readable
scenario_id such as ``test_seed9101_ep000``. No opaque hash of the whole seed
list is used, so every scenario can be traced back to its (seed, episode).
"""
from __future__ import annotations
import hashlib
import json
import math
import os

import numpy as np


def _cn(rng: np.random.Generator, *shape) -> np.ndarray:
    return (rng.standard_normal(shape) + 1j * rng.standard_normal(shape)) / math.sqrt(2.0)


def _sample_in_box(rng: np.random.Generator, box: np.ndarray) -> np.ndarray:
    return np.array([
        rng.uniform(box[0, 0], box[0, 1]),
        rng.uniform(box[1, 0], box[1, 1]),
        rng.uniform(box[2, 0], box[2, 1]),
    ])


def generate_scenario(env_cfg: dict, split: str, evaluation_seed: int,
                      episode_idx: int) -> dict:
    """Deterministically generate one scenario for (evaluation_seed, episode_idx).

    Geometry and channel use separate spawned streams so the geometry is
    independent of the channel trajectory.
    """
    K = int(env_cfg["num_users"])
    K_r = int(env_cfg["num_users_reflection"])
    N = int(env_cfg["num_ris_elements"])
    M = int(env_cfg["num_bs_antennas"])
    T = int(env_cfg["max_steps"])
    area_r = np.array(env_cfg["user_area_reflection"], dtype=np.float64)
    area_t = np.array(env_cfg["user_area_transmission"], dtype=np.float64)

    ss = np.random.SeedSequence(entropy=int(evaluation_seed),
                                spawn_key=(int(episode_idx),))
    geo_ss, chan_ss = ss.spawn(2)
    geo_rng = np.random.default_rng(geo_ss)
    chan_rng = np.random.default_rng(chan_ss)

    positions = np.zeros((K, 3), dtype=np.float64)
    for k in range(K_r):
        positions[k] = _sample_in_box(geo_rng, area_r)
    for k in range(K_r, K):
        positions[k] = _sample_in_box(geo_rng, area_t)

    return {
        "scenario_id": f"{split}_seed{int(evaluation_seed)}_ep{int(episode_idx):03d}",
        "split": split,
        "evaluation_seed": int(evaluation_seed),
        "episode_idx": int(episode_idx),
        "user_positions": positions,
        "h_d_small0": _cn(chan_rng, K, M),
        "G_small0": _cn(chan_rng, N, M),
        "g_small0": _cn(chan_rng, K, N),
        # One innovation per transition t -> t+1 (T entries covers max_steps).
        "innov_h_d": _cn(chan_rng, T, K, M),
        "innov_G": _cn(chan_rng, T, N, M),
        "innov_g": _cn(chan_rng, T, K, N),
    }


class ScenarioBank:
    """A list of deterministic scenarios plus provenance/hash bookkeeping."""

    def __init__(self, env_cfg: dict, split: str, evaluation_seeds: list[int],
                 episodes_per_seed: int):
        self.env_cfg = dict(env_cfg)
        self.split = str(split)
        self.evaluation_seeds = [int(s) for s in evaluation_seeds]
        self.episodes_per_seed = int(episodes_per_seed)
        self.scenarios = []
        for eval_seed in self.evaluation_seeds:
            for ep in range(self.episodes_per_seed):
                self.scenarios.append(
                    generate_scenario(env_cfg, split, eval_seed, ep))

    def __len__(self) -> int:
        return len(self.scenarios)

    def __getitem__(self, i: int) -> dict:
        return self.scenarios[i]

    # ------------------------------------------------------------ persistence
    def content_hash(self) -> str:
        h = hashlib.sha256()
        for sc in self.scenarios:
            h.update(sc["scenario_id"].encode())
            for key in ("user_positions", "h_d_small0", "G_small0", "g_small0",
                        "innov_h_d", "innov_G", "innov_g"):
                h.update(np.ascontiguousarray(sc[key]).tobytes())
        return h.hexdigest()

    def metadata(self) -> dict:
        relevant = {k: self.env_cfg.get(k) for k in (
            "num_bs_antennas", "num_users", "num_users_reflection", "num_ris_elements", "max_steps",
            "user_area_reflection", "user_area_transmission", "channel_rho")}
        return {
            "split": self.split,
            "evaluation_seeds": self.evaluation_seeds,
            "episodes_per_seed": self.episodes_per_seed,
            "n_scenarios": len(self.scenarios),
            "env_cfg_relevant": relevant,
            "scenarios": [
                {"scenario_id": sc["scenario_id"], "split": sc["split"],
                 "evaluation_seed": sc["evaluation_seed"],
                 "episode_idx": sc["episode_idx"]}
                for sc in self.scenarios],
            "content_sha256": self.content_hash(),
        }

    def save(self, json_path: str, npz_path: str) -> None:
        os.makedirs(os.path.dirname(json_path) or ".", exist_ok=True)
        arrays = {}
        for i, sc in enumerate(self.scenarios):
            for key in ("user_positions", "h_d_small0", "G_small0", "g_small0",
                        "innov_h_d", "innov_G", "innov_g"):
                arrays[f"s{i:04d}__{key}"] = sc[key]
        np.savez_compressed(npz_path, **arrays)
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(self.metadata(), f, indent=2)

    @classmethod
    def load(cls, json_path: str, npz_path: str) -> "ScenarioBank":
        with open(json_path, "r", encoding="utf-8") as f:
            meta = json.load(f)
        data = np.load(npz_path)
        bank = cls.__new__(cls)
        bank.env_cfg = {}
        bank.split = meta["split"]
        bank.evaluation_seeds = [int(s) for s in meta["evaluation_seeds"]]
        bank.episodes_per_seed = int(meta["episodes_per_seed"])
        bank.scenarios = []
        for i, sc_meta in enumerate(meta["scenarios"]):
            sc = dict(sc_meta)
            for key in ("user_positions", "h_d_small0", "G_small0", "g_small0",
                        "innov_h_d", "innov_G", "innov_g"):
                sc[key] = data[f"s{i:04d}__{key}"]
            bank.scenarios.append(sc)
        return bank


def build_eval_bank(cfg: dict, split: str) -> "ScenarioBank":
    """Build ONE evaluation bank for the requested split.

    Locked-test isolation (V4 review P0-3): training jobs must call this with
    split="validation" only, so the locked test ScenarioBank is never
    materialized inside a train-only/smoke/pilot process. The test bank may be
    constructed only by the final evaluation/aggregate job.
    """
    if split not in ("validation", "test", "dev", "legacy_eval"):
        raise ValueError(f"Unknown scenario split: {split!r}")
    env_cfg = cfg["env"]
    n_eps = int(cfg["evaluation"]["num_episodes"])
    seeds = list(cfg["evaluation"][f"{split}_seeds"])
    return ScenarioBank(env_cfg, split=split, evaluation_seeds=seeds,
                        episodes_per_seed=n_eps)


def build_eval_banks(cfg: dict) -> dict[str, "ScenarioBank"]:
    """Build the validation AND test banks (evaluation/aggregate jobs only).

    validation: `evaluation.validation_seeds` (legacy seeds 11..55, inspected
      during development -- NOT usable as a test set).
    test: `evaluation.test_seeds` (locked, previously unused).
    Each seed contributes `evaluation.num_episodes` scenarios; the scenario_id
    encodes split, seed and episode index for full auditability.

    Training jobs must NOT call this: use build_eval_bank(cfg, "validation").
    """
    return {split: build_eval_bank(cfg, split) for split in ("validation", "test")}
